networks:
  neo:

services:
  neo1:
    hostname: neo1
    container_name: neo1
    image: neo4j:4.4-enterprise
    env_file:
      - ../env/base_4.4.env
    networks:
      - neo
    ports:
      - 8473:7473
      - 8474:7474
      - 8687:7687
    volumes:
      - $PWD/docker/certs/volumes/data:/data
      - $PWD/docker/certs/volumes/logs:/logs
      - $PWD/docker/certs/volumes/backup:/tmp
      - $PWD/docker/certs/volumes/conf:/var/lib/neo4j/conf
      - $PWD/docker/certs/volumes/certs:/var/lib/neo4j/certificates
